import {IVFTaskType} from '@libs/data-layer/apps/clinic-ivf/enums'
import {PatientNoteTypeEnum} from '@libs/services-common/enums'

export const IVFTaskToPatientNoteMapper = {
  [IVFTaskType.SetupWorksheet]: PatientNoteTypeEnum.SetupWorksheet + '123',
  [IVFTaskType.LabelTubes]: PatientNoteTypeEnum.LabelTubes + '123',
  [IVFTaskType.LabelDishes]: PatientNoteTypeEnum.LabelDishes + '123',
  [IVFTaskType.VerifyConsent]: PatientNoteTypeEnum.VerifyConsent + '123',
  [IVFTaskType.RinseDishes]: PatientNoteTypeEnum.RinseDishes + '123',
  [IVFTaskType.DispenseMedia]: PatientNoteTypeEnum.DispenseMedia + '123',
  [IVFTaskType.PlaceIntoIncubators]: PatientNoteTypeEnum.PlaceIntoIncubators + '123',
  [IVFTaskType.VerifyHepBcHiv]: PatientNoteTypeEnum.VerifyHepBcHiv + '123',
  [IVFTaskType.OocyteCollection]: PatientNoteTypeEnum.OocyteCollection + '123',
  [IVFTaskType.SpermWash]: PatientNoteTypeEnum.SpermWash + '123',
  [IVFTaskType.PostStripping]: PatientNoteTypeEnum.PostStripping + '123',
  [IVFTaskType.MatureOocyteGroupPhoto]: PatientNoteTypeEnum.MatureOocyteGroupPhoto + '123',
  [IVFTaskType.IcsiInjection]: PatientNoteTypeEnum.IcsiInjection + 'note',
  [IVFTaskType.InjectionAssessment]: PatientNoteTypeEnum.InjectionAssessment + '321',
  [IVFTaskType.InseminationIVF]: PatientNoteTypeEnum.InseminationIVF + '321',
  [IVFTaskType.PICSI]: PatientNoteTypeEnum.PICSI + '321',
  [IVFTaskType.CaIonophore]: PatientNoteTypeEnum.CaIonophore + '321',
  [IVFTaskType.MiiDay1Cryo]: PatientNoteTypeEnum.MiiDay1Cryo + '321',
  [IVFTaskType.FertilizationCheck]: PatientNoteTypeEnum.FertilizationCheck + '321',
  [IVFTaskType.ChangeOver]: PatientNoteTypeEnum.ChangeOver + '321',
  [IVFTaskType.Day3Check]: PatientNoteTypeEnum.Day3Check + '321',
  [IVFTaskType.Day5Check]: PatientNoteTypeEnum.Day5Check + '321',
  [IVFTaskType.Day6Check]: PatientNoteTypeEnum.Day6Check + '321',
  [IVFTaskType.Day7Check]: PatientNoteTypeEnum.Day7Check + '321',
  [IVFTaskType.FrozenEmbryoTransfer]: PatientNoteTypeEnum.FreezingEmbryos + '321',
  [IVFTaskType.FinalBlastocystCryo]: PatientNoteTypeEnum.FinalBlastocystCryo + '321',
  [IVFTaskType.EmbryoGroupPhoto]: PatientNoteTypeEnum.EmbryoGroupPhoto + '321',
  [IVFTaskType.OocyteFreezing]: PatientNoteTypeEnum.OocyteCollection + '321',
  [IVFTaskType.PrintLabel]: PatientNoteTypeEnum.PrintLabel + '321',
  [IVFTaskType.CallThePatient]: PatientNoteTypeEnum.CallThePatient + '321',
  [IVFTaskType.JourneyWitness]: PatientNoteTypeEnum.JourneyWitness + '321',
}
