export enum AuditUserAction {
  Create = 'Create',
  Update = 'Update',
  Delete = 'Delete',
}

export enum AuditTrailCollection {
  PatientsRevisions = 'patients_revisions',
  PatientDetailRevisions = 'patient_detail_revisions',
  PatientDetailFemaleRevisions = 'patient_detail_female_revisions',
  PatientDetailMaleRevisions = 'patient_detail_male_revisions',
  PatientAddressRevisions = 'patient_address_revisions',
  PatientNoteRevisions = 'patient_note_revisions',
  PatientEctopicPregnancyHistoryRevisions = 'patient_ectopic_pregnancy_history_revisions',
  PatientFamilyHealthProblemRevisions = 'patient_family_health_problem_revisions',
  PatientFullTermDeliveryHistoryRevisions = 'patient_full_term_delivery_history_revisions',
  PatientPreTermDeliveryHistoryRevisions = 'patient_pre_term_delivery_history_revisions',
  PatientMiscarriageHistoryRevisions = 'patient_miscarriage_history_revisions',
  PatientAbortionHistoryRevisions = 'patient_abortion_history_revisions',
  PatientDoctorRevisions = 'patient_doctor_revisions',
  PatientPastSurgeryRevisions = 'patient_past_surgery_revisions',
  PatientPreviousFertilityTreatmentRevisions = 'patient_previous_fertility_treatment_revisions',
  PatientVitaminSupplementRevisions = 'patient_vitamin_supplement_revisions',
  PatientMedicationRevisions = 'patient_medication_revisions',
  PatientPrescriptionRevisions = 'patient_prescription_revisions',
  PatientEncounterRevisions = 'patient_encounter_revisions',
  PatientStaffNoteRevisions = 'patient_staff_note_revisions',
  PatientAddendumRevisions = 'patient_addendum_revisions',
  PatientDocumentRevisions = 'patient_document_revisions',
  PatientReferralRevisions = 'patient_referral_revisions',
  PatientAlertRevisions = 'patient_alert_revisions',
  PatientPharmacyRevisions = 'patient_pharmacy_revisions',

  PatientPlanRevisions = 'patient_plan_revisions',
  PatientPlanSheetRevisions = 'patient_plan_sheet_revisions',
  PatientPlanSheetAdditionalDayRevisions = 'patient_plan_sheet_additional_day_revisions',
  PatientPlanSheetActionRevisions = 'patient_plan_sheet_action_revisions',
  PatientPlanChecklistItemRevisions = 'patient_plan_checklist_item_revisions',
  PatientPlanAlertRevisions = 'patient_plan_alert_revisions',
  PatientPlanDetailRevisions = 'patient_plan_detail_revisions',
  PatientMilestoneRevisions = 'patient_milestone_revisions',
  PatientScheduledMilestoneRevisions = 'patient_scheduled_milestone_revisions',
  PatientPlanToTestTypeProcedureRevisions = 'patient_plan_to_test_type_procedure_revisions',
  PatientPlanToEndometrialAssessmentRevisions = 'patient_plan_to_endometrial_assessment_revisions',
  PatientPlanAddonRevisions = 'patient_plan_addon_revisions',
  PlanMedicationRevisions = 'plan_medication_revisions',
  PlanInitialResultRevisions = 'plan_initial_result_revisions',
  PatientPlanSpermSourceRevisions = 'patient_plan_sperm_source_revisions',
  PatientPlanLabInstructionRevisions = 'patient_plan_lab_instruction_revisions',
  PatientPlanLutealSupportItemRevisions = 'patient_plan_luteal_support_item_revisions',
  PatientPlanEmbryoTypeTransferInstructionRevisions = 'patient_plan_embryo_type_transfer_instruction_revisions',
  PatientPlanCohortIvfTaskMatureOocyteGroupPhotoRevisions = 'patient_plan_cohort_ivf_task_mature_oocyte_group_photo_revisions',
  PatientPlanCohortRevisions = 'patient_plan_cohort_revisions',
  PatientPlanCohortIvfTaskGroupRevisions = 'patient_plan_cohort_ivf_task_group_revisions',
  PatientProfileAlert = 'patient_profile_alert_revisions',

  TestOrderRevisions = 'test_order_revisions',
  TestOrderItemRevisions = 'test_order_item_revisions',
  TestOrderCommentRevisions = 'test_order_comment_revisions',
  SpecimenRevisions = 'specimen_revisions',
  SpecimenTestRevisions = 'specimen_test_revisions',
  TestResultRevisions = 'test_result_revisions',
  TestResultAttachmentRevisions = 'test_result_attachment_revisions',
  TestResultMeasurementRevisions = 'test_result_measurement_revisions',
  TestResultObservationRevisions = 'test_result_observation_revisions',
  TransportFolderRevisions = 'transport_folder_revisions',
  LabSyncObservationRequestRevisions = 'lab_sync_observation_request_revisions',
  LabSyncRawDataRepositoryRevisions = 'lab_sync_raw_data_repository_revisions',
  LabSyncObservationResultRevisions = 'lab_sync_observation_result_revisions',
  TestResultUterusMeasurementRevisions = 'test_result_uterus_measurement_revisions',
  TestResultOvaryMeasurementRevisions = 'test_result_ovary_measurement_revisions',
  TestResultOvaryCystMeasurementRevisions = 'test_result_ovary_cyst_measurement_revisions',
  TestResultUltrasoundFinalReportRevisions = 'test_result_ultrasound_final_report_revisions',
  TestResultObUltrasoundRevisions = 'test_result_ob_ultrasound_revisions',
  TestResultOHSSUltrasoundRevisions = 'test_result_ohss_ultrasound_revisions',

  SchedulingTemplateRevisions = 'scheduling_template_revisions',
  SchedulingTemplatePeriodRevisions = 'scheduling_template_period_revisions',

  AppointmentRevisions = 'appointment_revisions',

  TaskRevisions = 'task_revisions',

  OHIPClaimRevisions = 'ohip_claim_revisions',
  OHIPClaimToCodeRevisions = 'ohip_claim_to_code_revisions',
  PatientAdhocPaymentRevisions = 'patient_adhoc_payment_revisions',

  PaymentOrderRevisions = 'payment_order_revisions',
  PaymentOrderItemRevisions = 'payment_order_item_revisions',

  AppointmentAddonRevisions = 'appointment_addon_revisions',

  CryoCardRevisions = 'cryo_card_revisions',
  CryoSampleContainerRevisions = 'cryo_sample_container_revisions',
  CryoSampleDonorRevisions = 'cryo_sample_donor_revisions',

  PatientReportRevisions = 'patient_report_revisions',
  PatientFertilityIQRevisions = 'patient_fertility_iq_revisions',

  PatientConsentPackageRevisions = 'patient_consent_package_revisions',
  PatientConsentModuleRevisions = 'patient_consent_module_revisions',
  PatientConsentPackageSignatoryRevisions = 'patient_consent_package_signatory_revisions',

  PatientPaymentEstimateEmailAttemptsRevisions = 'patient_payment_estimate_email_attempt_revisions',
}
