import {IVFTaskType} from '@libs/data-layer/apps/clinic-ivf/enums'
import {
  Patient,
  PatientDetail,
  PatientDetailFemale,
  PatientDetailMale,
} from '@libs/data-layer/apps/users/entities/typeorm'

export enum PatientNoteTypeEnum {
  TryingForPregnancy = 'TryingForPregnancy',
  MonthsConceiving = 'MonthsConceiving',
  OvulationTracking = 'OvulationTracking',
  OvulationKitTimedIntercourse = 'OvulationKitTimedIntercourse',
  Lubricants = 'Lubricants',
  PreviousFertilitySpecialist = 'PreviousFertilitySpecialist',
  PreviousFertilityTreatment = 'PreviousFertilityTreatment',
  PreviousPregnancies = 'PreviousPregnancies',
  Period = 'Period',
  MenstrualCycleLength = 'MenstrualCycleLength',
  FirstDayOfLastPeriod = 'FirstDayOfLastPeriod',
  MenstrualFlow = 'MenstrualFlow',
  DaysOfBleeding = 'DaysOfBleeding',
  MenstrualPain = 'MenstrualPain',
  MenstrualClots = 'MenstrualClots',
  MenstrualSymptoms = 'MenstrualSymptoms',
  TakingBirthControl = 'TakingBirthControl',
  Ovulation = 'Ovulation',
  AnyPreviousPAPTest = 'AnyPreviousPAPTest',
  DateOfLastPAPTest = 'DateOfLastPAPTest',
  AbnormalPAP = 'AbnormalPAP',
  AbnormalPapProcedures = 'AbnormalPapProcedures',
  GynaecologicalConditions = 'GynaecologicalConditions',
  SignsOfPCOS = 'SignsOfPCOS',
  Hyperprolactinemia = 'Hyperprolactinemia',
  SignsOfPOI = 'SignsOfPOI',
  Breastfeeding = 'Breastfeeding',
  CervixTreatment = 'CervixTreatment',
  IntercoursePain = 'IntercoursePain',
  PreviousConception = 'PreviousConception',
  BiologicalChildren = 'BiologicalChildren',
  BiologicalChildrenWithCurrentPartner = 'BiologicalChildrenWithCurrentPartner',
  PastSemenAnalysis = 'PastSemenAnalysis',
  AbnormalResults = 'AbnormalResults',
  DiagnosedConditions = 'DiagnosedConditions',
  Vasectomy = 'Vasectomy',
  VasectomyReversal = 'VasectomyReversal',
  ErectionDifficulties = 'ErectionDifficulties',
  UndescendedTesticles = 'UndescendedTesticles',
  TesticularIssues = 'TesticularIssues',
  Toxins = 'Toxins',
  Infections = 'Infections',
  GenitalSurgery = 'GenitalSurgery',
  PatientID = 'PatientID',
  PatientName = 'PatientName',
  PreferredName = 'PreferredName',
  PrimaryPatientContribution = 'PrimaryPatientContribution',
  PrimaryAddress = 'PrimaryAddress',
  MailingAddress = 'MailingAddress',
  EmailAddress = 'EmailAddress',
  PhoneNumber = 'PhoneNumber',
  Ohip = 'Ohip',
  MRP = 'MRP',
  FollowUpAppointment = 'FollowUpAppointment',
  PartnersInvolvedInJourney = 'PartnersInvolvedInJourney',
  SexAtBirth = 'SexAtBirth',
  CancerPatient = 'CancerPatient',
  Gender = 'Gender',
  SexualOrientation = 'SexualOrientation',
  Pronouns = 'Pronouns',
  RelationshipStatus = 'RelationshipStatus',
  DateOfBirth = 'DateOfBirth',
  Age = 'Age',
  CurrentOccupation = 'CurrentOccupation',
  ReferringPhysican = 'ReferringPhysican',
  FamilyPhysician = 'FamilyPhysician',
  Height = 'Height',
  Weight = 'Weight',
  BMI = 'BMI',
  OtherMedicalProblems = 'OtherMedicalProblems',
  PastSurgery = 'PastSurgery',
  ProblemsWithAnesthetics = 'ProblemsWithAnesthetics',
  VitaminSupplements = 'VitaminSupplements',
  DrugAllergy = 'DrugAllergy',
  FoodAllergy = 'FoodAllergy',
  IodineAllergy = 'IodineAllergy',
  LatexAllergy = 'LatexAllergy',
  PatientAlerts = 'PatientAlerts',
  UseOfCigarettes = 'UseOfCigarettes',
  UseOfAlcohol = 'UseOfAlcohol',
  UseOfMarijuana = 'UseOfMarijuana',
  UseOfRecreationalDrugs = 'UseOfRecreationalDrugs',
  RegularExercise = 'RegularExercise',
  StressLevel = 'StressLevel',
  SeeingTherapist = 'SeeingTherapist',
  FamilyHistoryOfHealthProblem = 'FamilyHistoryOfHealthProblem',
  STDHistory = 'STDHistory',
  Diet = 'Diet',
  ActiveConsultsList = 'ActiveConsultsList',
  AdditionalInformation = 'AdditionalInformation',
  Pharmacy = 'Pharmacy',
  HasProceduresDueAbnormalPAP = 'HasProceduresDueAbnormalPAP',

  PlanMonitoringLocation = 'PlanMonitoringLocation',
  PlanCycleNumber = 'PlanCycleNumber',
  PlanFollicleNumber = 'PlanFollicleNumber',
  PlanCycleLength = 'PlanCycleLength',
  PlanReportedDay1 = 'PlanReportedDay1',
  PlanExpectedDay1 = 'PlanExpectedDay1',
  PlanSpermSource = 'PlanSpermSource',
  PlanSpermType = 'PlanSpermType',
  PlanProcedure = 'PlanProcedure',
  PlanOutcome = 'PlanOutcome',
  PlanCancellationReason = 'PlanCancellationReason',

  PatientMedication = 'PatientMedication',
  PatientPartners = 'PatientPartners',

  PlanLinkedPlan = 'PlanLinkedPlan',
  PlanFirstDayOfCycle = 'PlanFirstDayOfCycle',
  PlanDateOfTransferOrIUI = 'PlanDateOfTransferOrIUI',
  PlanDateOfOvaluation = 'PlanDateOfOvaluation',
  PlanEstimatedDateOfConfinement = 'PlanEstimatedDateOfConfinement',
  PlanLastMenstrualPeriod = 'PlanLastMenstrualPeriod',
  PlanUltrasoundOB = 'PlanUltrasoundOB',
  PlanEctopicPrecautions = 'PlanEctopicPrecautions',
  PlanObservationRequired = 'PlanObservationRequired',
  PlanGTPAETALS = 'PlanGTPAETALS',
  PreviousPlansIVF = 'PreviousPlansIVF',
  PlanProtocol = 'PlanProtocol',
  PlanBodySurfaceArea = 'PlanBodySurfaceArea',
  PlanDayOneOfCycle = 'PlanDayOneOfCycle',
  PlanDiscontinueMedication = 'PlanDiscontinueMedication',
  PlanContributorOocyte = 'PlanContributorOocyte',
  PlanContributorUterus = 'PlanContributorUterus',
  PlanFrozenEggs = 'PlanFrozenEggs',
  PlanMockCycleType = 'PlanMockCycleType',
  PlanEggsToThaw = 'PlanEggsToThaw',
  PlanEggStatus = 'PlanEggStatus',
  PlanEndometrialAssessment = 'PlanEndometrialAssessment',
  PlanFertilisationDirective = 'PlanFertilisationDirective',
  PlanGeneticTesting = 'PlanGeneticTesting',
  PlanFreshEmbryoTransfer = 'PlanFreshEmbryoTransfer',
  PlanInstructionsEmbryoTransferAndCryo = 'PlanInstructionsEmbryoTransferAndCryo',
  PlanInstructionsIVFRetrievalOrder = 'PlanInstructionsIVFRetrievalOrder',
  PlanInstructionsEggFreeze = 'PlanInstructionsEggFreeze',
  PlanInstructionsFET = 'PlanInstructionsFET',
  PlanAdditionalInfo = 'PlanAdditionalInfo',
  PlanAlert = 'PlanAlert',
  PlanTestOrders = 'PlanTestOrders',
  PlanEggQualityAnalysis = 'PlanEggQualityAnalysis',
  PlanFrozenEggsToThaw = 'PlanFrozenEggsToThaw',

  PlanStimSheet = 'PlanStimSheet',
  PlanStimSheetDay = 'PlanStimSheetDay',
  PlanPrimingWorksheet = 'PlanPrimingWorksheet',
  PlanPrimingWorksheetDay = 'PlanPrimingWorksheetDay',
  PlanOBSheet = 'PlanOBSheet',
  PlanOBSheetDay = 'PlanOBSheetDay',
  PlanHCGSheet = 'PlanHCGSheet',
  PlanHCGSheetDay = 'PlanHCGSheetDay',
  PlanEPLSheet = 'PlanEPLSheet',
  PlanEPLSheetDay = 'PlanEPLSheetDay',
  PlanOrderStimSheetDay = 'PlanOrderStimSheetDay',
  PlanOrderPrimingWorkSheetDay = 'PlanOrderPrimingWorkSheetDay',
  PlanOrderOBSheetDay = 'PlanOrderOBSheetDay',
  PlanOrderHCGSheetDay = 'PlanOrderHCGSheetDay',
  PlanOrderEPLSheetDay = 'PlanOrderEPLSheetDay',
  PlanTestResults = 'PlanTestResults',
  PlanFrozenEmbryoTransfter = 'PlanFrozenEmbryoTransfter',
  PlanRhogamOrWinRhoRequired = 'PlanRhogamOrWinRhoRequired',
  PlanSpontaneousBleeding = 'PlanSpontaneousBleeding',
  PlanLutealSupport = 'PlanLutealSupport',
  PlanChecklistItem = 'PlanChecklistItem',

  Diagnosis = 'Diagnosis',

  // IVF Lab
  SetupWorksheet = IVFTaskType.SetupWorksheet,
  LabelTubes = IVFTaskType.LabelTubes,
  LabelDishes = IVFTaskType.LabelDishes,
  VerifyConsent = IVFTaskType.VerifyConsent,
  RinseDishes = IVFTaskType.RinseDishes,
  DispenseMedia = IVFTaskType.DispenseMedia,
  PlaceIntoIncubators = IVFTaskType.PlaceIntoIncubators,
  VerifyHepBcHiv = IVFTaskType.VerifyHepBcHiv,
  OocyteCollection = IVFTaskType.OocyteCollection,
  SpermWash = IVFTaskType.SpermWash,
  PostStripping = IVFTaskType.PostStripping,
  MatureOocyteGroupPhoto = IVFTaskType.MatureOocyteGroupPhoto,
  IcsiInjection = IVFTaskType.IcsiInjection,
  InjectionAssessment = IVFTaskType.InjectionAssessment,
  InseminationIVF = IVFTaskType.InseminationIVF,
  PICSI = IVFTaskType.PICSI,
  EggsToThaw = IVFTaskType.EggsToThaw,
  CaIonophore = IVFTaskType.CaIonophore,
  MiiDay1Cryo = IVFTaskType.MiiDay1Cryo,
  FertilizationCheck = IVFTaskType.FertilizationCheck,
  Day3Check = IVFTaskType.Day3Check,
  Day5Check = IVFTaskType.Day5Check,
  Day6Check = IVFTaskType.Day6Check,
  Day7Check = IVFTaskType.Day7Check,
  FreezingEmbryos = IVFTaskType.FrozenEmbryoTransfer,
  FinalBlastocystCryo = IVFTaskType.FinalBlastocystCryo,
  EmbryoGroupPhoto = IVFTaskType.EmbryoGroupPhoto,
  PrintLabel = IVFTaskType.PrintLabel,
  ChangeOver = IVFTaskType.ChangeOver,
  CallThePatient = IVFTaskType.CallThePatient,
  JourneyWitness = IVFTaskType.JourneyWitness,
  DishInventory = IVFTaskType.DishInventory,
  PartnerDishInventory = IVFTaskType.PartnerDishInventory,
}

export const PatientNoteTypeNotEditableFields = [
  PatientNoteTypeEnum.PatientID,
  PatientNoteTypeEnum.EmailAddress,
  PatientNoteTypeEnum.PhoneNumber,
  PatientNoteTypeEnum.Age,
  PatientNoteTypeEnum.SexAtBirth,
  PatientNoteTypeEnum.MRP,
  PatientNoteTypeEnum.CancerPatient,
]

export const PatientFertilityHistoryNoteTypes = [
  PatientNoteTypeEnum.TryingForPregnancy,
  PatientNoteTypeEnum.MonthsConceiving,
  PatientNoteTypeEnum.OvulationTracking,
  PatientNoteTypeEnum.OvulationKitTimedIntercourse,
  PatientNoteTypeEnum.Lubricants,
  PatientNoteTypeEnum.PreviousFertilitySpecialist,
  PatientNoteTypeEnum.PreviousFertilityTreatment,
]

export const PatientMenstrualCycleNoteTypes = [
  PatientNoteTypeEnum.Period,
  PatientNoteTypeEnum.MenstrualCycleLength,
  PatientNoteTypeEnum.FirstDayOfLastPeriod,
  PatientNoteTypeEnum.MenstrualFlow,
  PatientNoteTypeEnum.DaysOfBleeding,
  PatientNoteTypeEnum.MenstrualClots,
  PatientNoteTypeEnum.MenstrualPain,
  PatientNoteTypeEnum.MenstrualSymptoms,
]

export const PatientBackgroundInformationNoteTypes = [
  PatientNoteTypeEnum.SexAtBirth,
  PatientNoteTypeEnum.CancerPatient,
  PatientNoteTypeEnum.Gender,
  PatientNoteTypeEnum.SexualOrientation,
  PatientNoteTypeEnum.Pronouns,
  PatientNoteTypeEnum.RelationshipStatus,
  PatientNoteTypeEnum.DateOfBirth,
  PatientNoteTypeEnum.Age,
  PatientNoteTypeEnum.CurrentOccupation,
  PatientNoteTypeEnum.ReferringPhysican,
  PatientNoteTypeEnum.FamilyPhysician,
  PatientNoteTypeEnum.Pharmacy,
]

export const PatientGynaecologicalHistoryNoteTypes = [
  PatientNoteTypeEnum.TakingBirthControl,
  PatientNoteTypeEnum.Ovulation,
  PatientNoteTypeEnum.AnyPreviousPAPTest,
  PatientNoteTypeEnum.DateOfLastPAPTest,
  PatientNoteTypeEnum.AbnormalPAP,
  PatientNoteTypeEnum.AbnormalPapProcedures,
  PatientNoteTypeEnum.GynaecologicalConditions,
  PatientNoteTypeEnum.SignsOfPCOS,
  PatientNoteTypeEnum.Hyperprolactinemia,
  PatientNoteTypeEnum.SignsOfPOI,
  PatientNoteTypeEnum.Breastfeeding,
  PatientNoteTypeEnum.CervixTreatment,
  PatientNoteTypeEnum.IntercoursePain,
]

export const PatientGetGenitourinaryHistoryNoteTypes = [
  PatientNoteTypeEnum.PreviousConception,
  PatientNoteTypeEnum.BiologicalChildren,
  PatientNoteTypeEnum.BiologicalChildrenWithCurrentPartner,
  PatientNoteTypeEnum.PastSemenAnalysis,
  PatientNoteTypeEnum.AbnormalResults,
  PatientNoteTypeEnum.DiagnosedConditions,
  PatientNoteTypeEnum.Vasectomy,
  PatientNoteTypeEnum.VasectomyReversal,
  PatientNoteTypeEnum.ErectionDifficulties,
  PatientNoteTypeEnum.UndescendedTesticles,
  PatientNoteTypeEnum.TesticularIssues,
  PatientNoteTypeEnum.Toxins,
  PatientNoteTypeEnum.Infections,
  PatientNoteTypeEnum.GenitalSurgery,
]

export const PatientGeneralHealthNoteTypes = [
  PatientNoteTypeEnum.Height,
  PatientNoteTypeEnum.Weight,
  PatientNoteTypeEnum.BMI,
  PatientNoteTypeEnum.OtherMedicalProblems,
  PatientNoteTypeEnum.PastSurgery,
  PatientNoteTypeEnum.ProblemsWithAnesthetics,
  PatientNoteTypeEnum.VitaminSupplements,
  PatientNoteTypeEnum.DrugAllergy,
  PatientNoteTypeEnum.FoodAllergy,
  PatientNoteTypeEnum.IodineAllergy,
  PatientNoteTypeEnum.LatexAllergy,
  PatientNoteTypeEnum.UseOfCigarettes,
  PatientNoteTypeEnum.UseOfAlcohol,
  PatientNoteTypeEnum.UseOfMarijuana,
  PatientNoteTypeEnum.UseOfRecreationalDrugs,
  PatientNoteTypeEnum.RegularExercise,
  PatientNoteTypeEnum.StressLevel,
  PatientNoteTypeEnum.SeeingTherapist,
  PatientNoteTypeEnum.FamilyHistoryOfHealthProblem,
  PatientNoteTypeEnum.STDHistory,
  PatientNoteTypeEnum.Diet,
  PatientNoteTypeEnum.ActiveConsultsList,
  PatientNoteTypeEnum.AdditionalInformation,
]

export const PatientDetailNoteMap = new Map<keyof PatientDetail, PatientNoteTypeEnum>([
  ['heightInInches', PatientNoteTypeEnum.Height],
  ['weightInLbs', PatientNoteTypeEnum.Weight],
  ['medicalProblems', PatientNoteTypeEnum.OtherMedicalProblems],
  ['problemWithAnesthetics', PatientNoteTypeEnum.ProblemsWithAnesthetics],
  ['drugAllergies', PatientNoteTypeEnum.DrugAllergy],
  ['foodAllergies', PatientNoteTypeEnum.FoodAllergy],
  ['latexAllergy', PatientNoteTypeEnum.LatexAllergy],
  ['iodineAllergy', PatientNoteTypeEnum.IodineAllergy],
  ['smokeCigarettes', PatientNoteTypeEnum.UseOfCigarettes],
  ['drinkAlcohol', PatientNoteTypeEnum.UseOfAlcohol],
  ['useMarijuana', PatientNoteTypeEnum.UseOfMarijuana],
  ['recreationalDrugs', PatientNoteTypeEnum.UseOfRecreationalDrugs],
  ['exerciseRegularly', PatientNoteTypeEnum.RegularExercise],
  ['currentStressLevel', PatientNoteTypeEnum.StressLevel],
  ['seeCounsellorForStress', PatientNoteTypeEnum.SeeingTherapist],
  ['stdHistory', PatientNoteTypeEnum.STDHistory],
  ['diet', PatientNoteTypeEnum.Diet],
  ['activeConsultsList', PatientNoteTypeEnum.ActiveConsultsList],
  ['noteFromPatient', PatientNoteTypeEnum.AdditionalInformation],
  ['gender', PatientNoteTypeEnum.Gender],
  ['currentOccupation', PatientNoteTypeEnum.CurrentOccupation],
  ['hasCancer', PatientNoteTypeEnum.CancerPatient],
  ['sexualOrientation', PatientNoteTypeEnum.SexualOrientation],
  ['preferredPronouns', PatientNoteTypeEnum.Pronouns],
  ['relationshipStatus', PatientNoteTypeEnum.RelationshipStatus],
  ['preferredName', PatientNoteTypeEnum.PreferredName],
])

export const PatientDetailFemaleNoteMap = new Map<keyof PatientDetailFemale, PatientNoteTypeEnum>([
  ['firstDayOfLastPeriod', PatientNoteTypeEnum.FirstDayOfLastPeriod],
  ['menstrualFlow', PatientNoteTypeEnum.MenstrualFlow],
  ['daysOfBleeding', PatientNoteTypeEnum.DaysOfBleeding],
  ['menstrualPain', PatientNoteTypeEnum.MenstrualPain],
  ['menstrualClots', PatientNoteTypeEnum.MenstrualClots],
  ['isTryingForPregnancy', PatientNoteTypeEnum.TryingForPregnancy],
  ['monthsTryingToGetPregnant', PatientNoteTypeEnum.MonthsConceiving],
  ['menstrualSymptoms', PatientNoteTypeEnum.MenstrualSymptoms],
  ['takingBirthControl', PatientNoteTypeEnum.TakingBirthControl],
  ['usingAppToTrackOvulation', PatientNoteTypeEnum.OvulationTracking],
  ['abnormalPapProcedures', PatientNoteTypeEnum.AbnormalPapProcedures],
  ['gynaecologicalConditions', PatientNoteTypeEnum.GynaecologicalConditions],
  ['usingOvulationKits', PatientNoteTypeEnum.OvulationKitTimedIntercourse],
  ['seenFertilitySpecialist', PatientNoteTypeEnum.PreviousFertilitySpecialist],
  ['usingLubricants', PatientNoteTypeEnum.Lubricants],
  ['signsOfPCOS', PatientNoteTypeEnum.SignsOfPCOS],
  ['hyperprolactinemia', PatientNoteTypeEnum.Hyperprolactinemia],
  ['signsOfPOI', PatientNoteTypeEnum.SignsOfPOI],
  ['breastfeeding', PatientNoteTypeEnum.Breastfeeding],
  ['cervixTreatment', PatientNoteTypeEnum.CervixTreatment],
  ['intercoursePain', PatientNoteTypeEnum.IntercoursePain],
  ['hasProceduresDueAbnormalPAP', PatientNoteTypeEnum.HasProceduresDueAbnormalPAP],
  ['hasPeriod', PatientNoteTypeEnum.Period],
  ['daysBetweenPeriods', PatientNoteTypeEnum.MenstrualCycleLength],
])

export const PatientDetailMaleNoteMap = new Map<keyof PatientDetailMale, PatientNoteTypeEnum>([
  ['previousConception', PatientNoteTypeEnum.PreviousConception],
  ['haveBiologicalChildren', PatientNoteTypeEnum.BiologicalChildren],
  ['hadSemenAnalysis', PatientNoteTypeEnum.PastSemenAnalysis],
  ['semenAnalysisIsNormal', PatientNoteTypeEnum.AbnormalResults],
  [
    'haveBiologicalChildrenWithCurrentPartner',
    PatientNoteTypeEnum.BiologicalChildrenWithCurrentPartner,
  ],
  ['diagnosedConditions', PatientNoteTypeEnum.DiagnosedConditions],
  ['vasectomy', PatientNoteTypeEnum.Vasectomy],
  ['vasectomyReversal', PatientNoteTypeEnum.VasectomyReversal],
  ['erectionDifficulties', PatientNoteTypeEnum.ErectionDifficulties],
  ['undescendedTesticles', PatientNoteTypeEnum.UndescendedTesticles],
  ['testicularIssues', PatientNoteTypeEnum.TesticularIssues],
  ['toxins', PatientNoteTypeEnum.Toxins],
  ['infections', PatientNoteTypeEnum.Infections],
  ['genitalSurgery', PatientNoteTypeEnum.GenitalSurgery],
])

export const PatientNoteMap = new Map<keyof Patient, PatientNoteTypeEnum>([
  ['sexAtBirth', PatientNoteTypeEnum.SexAtBirth],
  ['dateOfBirth', PatientNoteTypeEnum.DateOfBirth],
  ['previousFertilityTreatments', PatientNoteTypeEnum.PreviousFertilityTreatment],
  ['patientIdentifier', PatientNoteTypeEnum.PatientID],
  ['ohipCardNumber', PatientNoteTypeEnum.Ohip],
])
