export enum AuthTypes {
  AppCheck = 'AppCheck',
  FirebaseIdTokenWithoutEmail = 'FirebaseIdTokenWithoutEmail',
  FirebaseSession = 'FirebaseSession',
  FirebaseSessionPhoneMFA = 'FirebaseSessionPhoneMFA',
  SAMLAuthProviderGoogle = 'SAMLAuthProviderGoogle',
  PubSubBackgroundTask = 'PubSubBackgroundTask',
}

export enum AuthMFAfactorTypes {
  Phone = 'phone',
}

export enum SystemAuthUserId {
  UltrasoundReportHandler = 'ultrasound-report-handler',
  UltrasoundResultCreator = 'ultrasound-result-creator',
  UltrasoundFinalReportHandler = 'ultrasound-final-report-handler',
  BloodSpecimenCreator = 'blood-specimen-creator',
  CryoSpecimenCreator = 'cryo-specimen-creator',
  SemenSpecimenCreator = 'semen-specimen-creator',
  SingleSpecimenCreator = 'single-specimen-creator',
  SwabSpecimenCreator = 'swab-specimen-creator',
  SpecimenResultCreator = 'specimen-result-creator',
  OrderItemResultCreator = 'order-item-result-creator',
  SpecimenMilestoneHandler = 'specimen-milestone-handler',
  QuestionnaireAnswersMapper = 'questionnaire-answers-mapper',
  AudtomatedTaskCreator = 'automated-task-creator',
  PullResultsFromDynacareHandler = 'pull-results-from-dynacare-handler',
  PullResultsFromLifeLabsHandler = 'pull-results-from-life-labs-handler',
  ResultReceivedFromRoche = 'result-received-from-roche',
  CompleteInProgressAppointments = 'complete-in-progress-appointments',
  MilestoneStatusChanger = 'milestone-status-changer',
  MilestoneUpdater = 'milestone-updater',
  ScheduledMilestoneCreator = 'scheduled-milestone-creator',
  UpdatePatientStatusHandler = 'update-patient-status-handler',
  UpdateHasSameSexPartner = 'update-has-same-sex-partner',
  DeactivatePatientHandler = 'deactivate-patient-handler',
  AcuitySyncAppointmentCreated = 'acuity-sync-apppointment-created',
  ChatConversationCreatedHandler = 'chat-conversation-handler',
  RestoreQuestionnaireIntentForPatientIntakeCommand = 'RestoreQuestionnaireIntentForPatientIntakeCommand',
  HandlerParseAndSyncLabHL7 = 'HandlerParseAndSyncLabHL7',
  PatientProfileAlertHandler = 'PatientProfileAlertHandler',
  HandlerBulkDownloadGenerate = 'HandlerBulkDownloadGenerate',
  MarkOldExternalResultsAutoReviewedCommand = 'MarkOldExternalResultsAutoReviewedCommand',
  PatientPlanCreatedHandler = 'PatientPlanCreatedHandler',
  PatientPlanUpdatedHandler = 'PatientPlanUpdatedHandler',
  AppointmentCreatedHandler = 'AppointmentCreatedHandler',
  AppointmentUpdatedHandler = 'AppointmentUpdatedHandler',
  AppointmentCancellationHandler = 'AppointmentCancellationHandler',
}
