export const INVALID_ID_TOKEN = 'INVALID_ID_TOKEN'
export const INVALID_TENANT_ID_ERROR = 'INVALID_TENANT_ID_ERROR'
export const INVALID_IDENTITY_PROVIDER_ERROR = 'INVALID_IDENTITY_PROVIDER_ERROR'
export const CUSTOM_ID_TOKEN_USAGE_DISABLED = 'CUSTOM_ID_TOKEN_USAGE_DISABLED'
