export enum ConsentFunctions {
  GetPatientConsents = 'GetPatientConsents',
  SendConsents = 'SendConsents',
  GetConsentModules = 'GetConsentModules',
  GetConsentsStatuses = 'GetConsentsStatuses',
  UploadPaper = 'UploadPaper',
  SendConsentReminder = 'SendConsentReminder',
  ConsentPackageSentHandler = 'ConsentPackageSentHandler',
  PatientConsentPackageUpdated = 'PatientConsentPackageUpdated',
  GeneratePlanConsent = 'GeneratePlanConsent',
  SendConsentPackageSentEmail = 'SendConsentPackageSentEmail',
  SendConsentEmail = 'SendConsentEmail',
  DownloadConsentPackage = 'DownloadConsentPackage',
  GenerateConsentPackagePDF = 'GenerateConsentPackagePDF',
  PatientPlanHasConsent = 'PatientPlanHasConsent',
  PatientConsentPackageNotFound = 'PatientConsentPackageNotFound',
  PatientConsentPackageSignatoryNotFound = 'PatientConsentPackageSignatoryNotFound',
  PatientPlanNotFound = 'PatientPlanNotFound',
  PlanStatusNotChanged = 'PlanStatusNotChanged',
  PlanStatusNotReadyForActivation = 'PlanStatusNotReadyForActivation',
  SaveCopyToStorage = 'SaveCopyToStorage',
  VoidConsentPackage = 'VoidConsentPackage',
  GenerateConsentPackage = 'GenerateConsentPackage',
  CreateConsentPackageReminder = 'CreateConsentPackageReminder',
  SendPatientPackageReminder = 'SendPatientPackageReminder',
  CreatePatientConsentQuestionnaireBySignatures = 'CreatePatientConsentQuestionnaireBySignatures',
  SaveStatusHistory = 'SaveStatusHistory',
  PatientPlanHasConsentPackage = 'PatientPlanHasConsentPackage',
  SendConsentPackageSentEmailAndPush = 'SendConsentPackageSentEmailAndPush',
}

export enum ConsentActions {
  GetPatientConsentsFailed = 'GetPatientConsentsFailed',
  SendConsentsFailed = 'SendConsentsFailed',
  GetConsentModulesFailed = 'GetConsentModulesFailed',
  GetConsentsStatusesFailed = 'GetConsentsStatusesFailed',
  SendConsentReminderFailed = 'SendConsentReminderFailed',
  ConsentPackageSentHandlerFailed = 'ConsentPackageSentHandlerFailed',
  PatientConsentPackageUpdatedFailed = 'PatientConsentPackageUpdatedFailed',
  GeneratePlanConsentFailed = 'GeneratePlanConsentFailed',
  DownloadConsentPackageFailed = 'DownloadConsentPackageFailed',
  UploadPaperFailed = 'UploadPaperFailed',
  SaveCopyToStorageFailed = 'SaveCopyToStorageFailed',
  VoidConsentPackageFaield = 'VoidConsentPackageFailed',
  SavedToStorage = 'SavedToStorage',
  GenerateConsentPackageFailed = 'GenerateConsentPackageFailed',
  ConsentPackageGenerationNotRequired = 'ConsentPackageGenerationNotRequired',
  GetUniqueConsentModules = 'GetUniqueConsentModules',
  GetSignatoriesToRelationTypes = 'GetSignatoriesToRelationTypes',
  GetUniqueRelationTypes = 'GetUniqueRelationTypes',
  NoReminderRequired = 'NoReminderRequired',
  CloudTaskCreationFailed = 'CloudTaskCreationFailed',
  EmailSent = 'EmailSent',
  InternalError = 'InternalError',
  NoChange = 'NoChange',
}
