export enum DynacareAdapterFunctions {
  ValidateResponse = 'DynacareValidateResponse',
  GetNotifications = 'DynacareGetNotifications',
  GetOrderAttachments = 'DynacareGetOrderAttachments',
  GetResults = 'DynacareGetResults',
  PullResults = 'DynacarePullResults',
  ParseHL7Result = 'DynacareParseHL7Result',
  UpdateResultFromDynacare = 'UpdateResultFromDynacare',
  UploadHl7Result = 'UploadHl7Result',
  HandlerPullResultsFromDynacare = 'HandlerPullResultsFromDynacare',
  ProcessDynacareNotifications = 'ProcessDynacareNotifications',
  FormatDynacareDateOfBirth = 'FormatDynacareDateOfBirth',
  FormatDynacareSpecimenCollectionDate = 'FormatDynacareSpecimenCollectionDate',
}

export enum DynacareAdapterActions {
  DraftRawResultCreated = 'DynacareDraftRawResultCreated',
  AttachmentAvailable = 'DynacareAttachmentAvailable',
  ResultReceived = 'DynacareResultReceived',
  FileUploaded = 'DynacareFileUploaded',
  MarkedAsPending = 'DynacareMarkedAsPending',
  ValidationFailed = 'DynacareValidationFailed',
  RequestFailed = 'DynacareRequestFailed',
  AcknowledgementSuccess = 'DynacareAcknowledgementSuccess',
  GetResultWith401Response = 'GetResultWith401Response',
  XMLParseFailed = 'DynacareXMLParseFailed',
  ResultNotFound = 'ResultNotFound',
  ResponseReceived = 'DynacareResponseReceived',
  NoPendingNotifications = 'DynacareNoPendingNotifications',
  AllNotificationAcknowledged = 'DynacareAllNotificationAcknowledged',
  AttachmentNotAvailable = 'DynacareAttachmentNotAvailable',
  AttachmentStorageReferenceError = 'DynacareAttachmentStorageReferenceError',
  AcknowledgementFailed = 'DynacareAcknowledgementFailed',
  ResultPullFailed = 'DynacareResultPullFailed',
  ProcessDynacareNotificationsFailed = 'ProcessDynacareNotificationsFailed',
  HL7ParseFailed = 'DynacareHL7ParseFailed',
  DataMappingFailed = 'DynacareDataMappingFailed',
  EmptyOBXSegments = 'DynacareEmptyOBXSegments',
  OHIPNumberMissing = 'DynacareOHIPNumberMissing',
  PatientNotFound = 'DynacarePatientNotFound',
  NoPendingResults = 'DynacareNoPendingResults',
  ResultMeasurementNotFound = 'DynacareResultMeasurementNotFound',
  MeasurementUpdateSkipped = 'DynacareMeasurementUpdateSkipped',
  UploadHl7ResultFailed = 'UploadHl7ResultFailed',
  CheckFeatureFlag = 'CheckFeatureFlag',
  FormatSpecimenCollectionDateFailed = 'FormatSpecimenCollectionDate',
  DOBFormatingFailed = 'DOBFormatingFailed',
}
