export enum PatientPrescriptionServiceFunctions {
  UpdatePatientPrescriptionStatus = 'UpdatePatientPrescriptionStatus',
  ArchivePatientPrescription = 'ArchivePatientPrescription',
  CreatePatientMedication = 'CreatePatientMedication',
  UpdatePatientMedication = 'UpdatePatientMedication',
  GetPatientPrescriptions = 'GetPatientPrescriptions',
  GetPatientMedications = 'GetPatientMedications',
  CreatePatientPrescription = 'CreatePatientPrescription',
  GetMedicationDropdownOptions = 'GetMedicationDropdownOptions',
  GetPatientMedicationsState = 'GetPatientMedicationsState',
  SavePatientMedicationHistory = 'SavePatientMedicationHistory',
  GetCreatePatientMedicationDataFromInternalDB = 'GetCreatePatientMedicationDataFromInternalDB',
  GetPatientMedicationPayloadFromDrugBank = 'GetPatientMedicationPayloadFromDrugBank',
  SavePatientMedicationHistoryArray = 'SavePatientMedicationHistoryArray',
  GetPrescriptionDetails = 'GetPrescriptionDetails',
  UpdatePatientPrescriptions = 'UpdatePatientPrescriptions',
}
export enum PatientPrescriptionServiceActions {
  UpdatePatientPrescriptionStatusFailed = 'UpdatePatientPrescriptionStatusFailed',
  ArchivePatientPrescriptionFailed = 'ArchivePatientPrescriptionFailed',
  CreatePatientMedicationFailed = 'CreatePatientMedicationFailed',
  CreatePatientPrescriptionFailed = 'CreatePatientPrescriptionFailed',
  GetPatientMedicationsFailed = 'GetPatientMedicationsFailed',
  PatientNotFound = 'PatientNotFound',
  MedicationNotFound = 'MedicationNotFound',
  MissingValuesFromDrugBank = 'MissingValuesFromDrugBank',
  StaffNotFound = 'StaffNotFound',
  GetPatientPrescriptionsFailed = 'GetPatientPrescriptionsFailed',
  UpdatePatientMedicationFailed = 'UpdatePatientMedicationFailed',
  GetMedicationDropdownOptionsFailed = 'GetMedicationDropdownOptionsFailed',
  GetPatientMedicationsStateFailed = 'GetPatientMedicationsStateFailed',
  SavePatientMedicationHistoryFailed = 'SavePatientMedicationHistoryFailed',
  GetPrescriptionDetailsFailed = 'GetPrescriptionDetailsFailed',
  UpdatePatientPrescriptionsFailed = 'UpdatePatientPrescriptionsFailed',
}
