export enum QuestionnaireFunctions {
  SubmitAndGetNextQuestion = 'SubmitAndGetNextQuestion',
  GetAnsweredQuestionAndValidate = 'GetAnsweredQuestionAndValidate',
  GetPreviousQuestion = 'GetPreviousQuestion',
  CreateQuestionnaireIntentOrAnswerNextQuestion = 'CreateQuestionnaireIntentOrAnswerNextQuestion',
  SaveFinalAnswers = 'SaveFinalAnswers',
  ValidateYearDropdownAnswers = 'ValidateYearDropdownAnswers',
  IsInvalidYearDropdownAnswer = 'IsInvalidYearDropdownAnswer',
  ThrowErrorYearDropdownOutOfRange = 'ThrowErrorYearDropdownOutOfRange',
  GetFlowDetails = 'GetFlowDetails',
  UpdatePatientJourneyType = 'UpdatePatientJourneyType',
  ValidateQuestionnaireOhip = 'ValidateQuestionnaireOhip',
  GetQuestionsWithAsnwerToValidate = 'GetQuestionsWithAsnwerToValidate',
}

export enum QuestionnaireActions {
  QuestionnaireIntentNotFound = 'QuestionnaireIntentNotFound',
  PatientNotFound = 'PatientNotFound',
  GetPreviousQuestionFailed = 'GetPreviousQuestionFailed',
  GetPreviousQuestion = 'GetPreviousQuestion',
  CreateIntentData = 'CreateIntentData',
  CreateIntentFailed = 'CreateIntentFailed',
  QuestionnaireNotFound = 'QuestionnaireNotFound',
  QuestionnaireAlreadyExists = 'QuestionnaireAlreadyExists',
  SubmitFailed = 'SubmitFailed',
  FinalAnswersSaveFailed = 'FinalAnswersSaveFailed',
  QuestionForAnswerNotFound = 'QuestionForAnswerNotFound',
  YearDropdownOutOfRange = 'YearDropdownOutOfRange',
  SkipValidateYearDropdown = 'SkipValidateYearDropdown',
  QuestionWithSequence1NotFoundDataError = 'QuestionWithSequence1NotFound_DataError',
  GetFlowDetailsFailed = 'GetFlowDetails',
  QuestionnaireIntentMissing = 'QuestionnaireIntentMissing',
  SubmitAndGetNextQuestion = 'SubmitAndGetNextQuestion',
  UpdatingPatientCurrentJourneyIntoShowAppointments = 'UpdatingPatientCurrentJourneyIntoShowAppointments',
  UpdatingPatientIsOhipValid = 'UpdatingPatientIsOhipValid',
  UpdatePatientAlertsOnQuestionnaireCompletion = 'UpdatePatientAlertsOnQuestionnaireCompletion',
  QuestionNotFound = 'QuestionNotFound',
  GroupQuestionNotSupported = 'GroupQuestionNotSupported',
  RepeatedQuestionNotSupported = 'RepeatedQuestionNotSupported',
}
