export enum StaffFunctions {
  GetPermissions = 'GetPermissions',
  GetPermissionsInDb = 'GetPermissionsInDb',
  GetStaffUser = 'GetStaffUser',
  GetCurrentStaffUserDefault = 'GetCurrentStaffUserDefault',
  SetCurrentStaffUserDefaults = 'SetCurrentStaffUserDefaults',
  DeleteByRoleIdsHandler = 'DeleteByRoleIdsHandler',
  DeleteByAuthUserIdHandler = 'DeleteByAuthUserIdHandler',
  UpdateBucketPermissionByUserIdHandler = 'UpdateBucketPermissionByUserIdHandler',
  UpdateBucketPermissionByRoleHandler = 'UpdateBucketPermissionByRoleHandler',
}
export enum StaffActions {
  GetPermissionsFailed = 'GetPermissionsFailed',
  GetPermissions = 'GetPermissions',
  GetPermissionsInDb = 'GetPermissionsInDb',
  GetStaffList = 'GetStaffList',
  GetStaffUserFailed = 'GetStaffUserFailed',
  GetCurrentStaffUserDefaultFailed = 'GetCurrentStaffUserDefaultFailed',
  SetCurrentStaffUserDefaultsFailed = 'SetCurrentStaffUserDefaultsFailed',
  DeletingPermissionCache = 'DeletingPermissionCache',
  OldPermissionCache = 'OldPermissionCache',
  DeletedPermissionCache = 'DeletedPermissionCache',
  DeleteByRoleIdsHandlerFailed = 'DeleteByRoleIdsHandlerFailed',
  BeginCF = 'BeginCF',
  UpdateBucketPermissionByUserIdHandlerFailed = 'UpdateBucketPermissionByUserIdHandlerFailed',
  StaffNotFound = 'StaffNotFound',
  RoleIdIsUndefined = 'RoleIdIsUndefined',
  NotFoundAnyForRoleId = 'NotFoundAnyForRoleId',
  UpdateBucketPermissionByRoleHandlerFailed = 'UpdateBucketPermissionByRoleHandlerFailed',
}
