export enum ProfileHighlightUIID {
  Partners = 'Partners',
  BMI = 'BMI',
  MRP = 'MRP',
  Menses = 'Menses',
  LatexAllergy = 'LatexAllergy',
  FoodAllergies = 'FoodAllergies',
  DrugAllergies = 'DrugAllergies',
  Medications = 'Medications',
  OtherProviders = 'OtherProviders',
  ContactInfo = 'ContactInfo',
  DoctorInfo = 'DoctorInfo',
  OHIPInfo = 'OHIPInfo',
  StimSheets = 'StimSheets',
}
