name: Continues Integration VM Cache Clean
on:
  workflow_dispatch:
  schedule:
    # Every day on midnight
    - cron: '0 0 * * *'

jobs:
  build:
    timeout-minutes: 60
    runs-on: be-ci-pool

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: VM cache cleanup
        uses: ./.github/actions/ci-clear-cache
