/* eslint-disable max-lines */
import {Appointment} from '@libs/data-layer/apps/scheduling/entities/typeorm/appointment.entity'
import {
  PatientEncounterAddendum,
  PatientEncounter,
  EncounterType,
  PatientStaffNoteAddendum,
  PatientStaffNote,
  StaffNoteType,
  Patient,
  PatientAbortionHistory,
  PatientDetail,
  PatientDetailFemale,
  PatientEctopicPregnancyHistory,
  PatientFullTermDeliveryHistory,
  PatientMedication,
  PatientMiscarriageHistory,
  PatientPartner,
  PatientPreTermDeliveryHistory,
  PatientVitaminSupplement,
  PatientDetailMale,
  PatientNote,
  PatientPastSurgery,
  PatientPreviousFertilityTreatment,
  PatientContactForm,
  PatientDoctor,
  PatientReferral,
  PatientPushNotification,
  PatientDocument,
  DocumentCategory,
  MilestoneServiceTypeLimitation,
  PatientEncounterAttachment,
  PatientEncounterAddendumAttachment,
  PatientStaffNoteAttachment,
  PatientStaffNoteAddendumAttachment,
  PatientPlanDiscontinuedMedication,
  PatientAdhocPayment,
  ProfileAlert,
  PatientProfileAlert,
  BulkDownloadRequest,
  BulkDownloadRequestItem,
  PatientFeedbackForm,
  PatientCryoSubscription,
  PatientCryoSubscriptionEvent,
  ConsentModule,
  PredefinedConsentPackage,
  PredefinedConsentPackageToModule,
  PatientConsentPackage,
  PatientConsentPackageSignatory,
  PatientConsentModule,
  PatientQuestionnaire,
  PatientQuestionnaireToQuestion,
  ConsentModuleToQuestion,
} from '@libs/data-layer/apps/users/entities/typeorm'
import {
  AppointmentMetadata,
  CatheterType,
  DefaultFilterForAppointmentToPatientStatus,
  DefaultFilterForAppointmentToServiceProvider,
  Introduction,
  SchedulingSlot,
  SchedulingTemplate,
  SchedulingTemplatePeriod,
  SchedulingTimeOffBlock,
  SchedulingTimeOffBlockPeriod,
  ServiceCategory,
  ServiceGroup,
  ServiceGroupAvailability,
  ServiceGroupToApplicationCode,
  ServiceGroupToServiceType,
  ServiceProvider,
  ServiceProviderToServiceType,
  ServiceType,
} from '@libs/data-layer/apps/scheduling/entities/typeorm'
import {PaymentOrder} from '@libs/data-layer/apps/checkout/entities/typeorm/payment-order.entity'
import {PaymentOrderItem} from '@libs/data-layer/apps/checkout/entities/typeorm/payment-order-item.entity'
import {AppliedSchedulingTemplatePeriod} from '@libs/data-layer/apps/scheduling/entities/typeorm/applied-template-period.entity'
import {ServiceTypeConstraint} from '@libs/data-layer/apps/scheduling/entities/typeorm/service-type-constraint.entity'
import {
  LabInfo,
  LabMachine,
  ProfileTestResult,
  SemenVerificationForm,
  Specimen,
  SpecimenGroup,
  SpecimenStorageLocation,
  SpecimenTest,
  TestGroup,
  TestGroupItem,
  TestOrder,
  TestOrderCancellationReason,
  TestOrderItem,
  TestOrderType,
  TestPanel,
  TestPanelToTestType,
  TestResult,
  TestResultAttachment,
  TestResultUterusMeasurement,
  TestResultMeasurement,
  TestResultOvaryCystMeasurement,
  TestResultOvaryMeasurement,
  TestType,
  TestTypeResultOption,
  TransportFolder,
  TestResultUltrasoundFinalReport,
  TestResultObUltrasound,
  TestOrderAction,
  SuperType,
  LabSyncRawData,
  LabSyncTestResultFieldMatch,
  LabSyncObservationRequest,
  LabSyncObservationResult,
  LabSyncObservationRequestStatusHistory,
  TestResultOHSSFluidMeasurement,
  TestResultOHSSOvaryMeasurement,
  ThyroidProtocolResult,
  ThyroidProtocolResultNote,
  PatientFertilityIQ,
  PatientFertilityIQFemale,
  TestResultSonoDetail,
  PatientFertilityIQTestResult,
  TestTypeConfiguration,
  TestTypeObservationType,
  TestObservationType,
  SpecimenDetailSyncStatusLog,
} from '@libs/data-layer/apps/clinic-test/entities/typeorm'
import {
  CryoCan,
  CryoCane,
  CryoTank,
  CryoVial,
  MediaLot,
  Reagent,
  CryoTankV2,
  CryoCanV2,
  CryoCaneV2,
  CryoSampleContainer,
  CryoSampleDonor,
  CryoInventoryCard,
  CryoDiscardReason,
  CryoInventoryCardExternalSample,
} from '@libs/data-layer/apps/clinic-cryo-preservation-lab/entities/typeorm'
import {CareTeam} from '@libs/data-layer/apps/users/entities/typeorm/care-team.entity'
import {PatientPrescription} from '@libs/data-layer/apps/users/entities/typeorm/patient-prescription.entity'
import {Pharmacy} from '@libs/data-layer/apps/users/entities/typeorm/pharmacy.entity'
import {ServiceProviderGroup} from '@libs/data-layer/apps/scheduling/entities/typeorm/service-provider-group.entity'
import {
  Medication,
  MedicationCategory,
  MedicationInstruction,
  MedicationInstructionStep,
  MedicationPredifinedDosage,
  MedicationToMedicationCategory,
} from '@libs/data-layer/apps/medication/entities/typeorm'
import {PatientToServiceProvider} from '@libs/data-layer/apps/users/entities/typeorm/patient-to-service-provider.entity'
import {
  PatientQuestionnaireAnswer,
  AnswerOption,
  ApplicationCode,
  Question,
  QuestionConstraint,
  Questionnaire,
  QuestionnaireToQuestion,
} from '@libs/data-layer/apps/questionnaires/entities/typeorm'
import {AfterVisitSummary} from '@libs/data-layer/apps/scheduling/entities/typeorm/after-visit-summary.entity'
import {PatientMilestone} from '@libs/data-layer/apps/users/entities/typeorm/patient-milestone.entity'
import {PatientDefaultMilestone} from '@libs/data-layer/apps/users/entities/typeorm/default-milestone.entity'
import {PatientAlert} from '@libs/data-layer/apps/users/entities/typeorm/patient-alert.entity'
import {PatientAddress} from '@libs/data-layer/apps/users/entities/typeorm/patient-address.entity'
import {PatientMilestoneToAppointment} from '@libs/data-layer/apps/users/entities/typeorm/patient-milestone-to-appointment.entity'
import {SpecimenIncompletionReason} from '@libs/data-layer/apps/clinic-test/entities/typeorm/specimen-incompletion-reason.entity'
import {
  AutomatedTask,
  ExternalDoctor,
  Permission,
  Role,
  Staff,
  StaffDefault,
  Task,
  TaskTemplate,
} from '@libs/data-layer/apps/clinic-tasks/entities'
import {TaskReassignment} from '@libs/data-layer/apps/clinic-tasks/entities/task-reassignment.entity'
import {PatientFamilyHealthProblem} from '@libs/data-layer/apps/users/entities/typeorm/patient-family-health-problem.entity'
import {PatientCustomAlert} from '@libs/data-layer/apps/users/entities/typeorm/patient-custom-alert.entity'
import {
  PatientPlan,
  PatientPlanChangeNotificationEntity,
  PatientPlanDetail,
  PatientPlanEmbryoTypeTransferInstruction,
  PatientPlanGeneticTesting,
  PatientPlanSheet,
  PatientPlanSheetAdditionalDay,
  PatientPlanStatus,
  PatientScheduledMilestone,
  PlanCategory,
  PlanInitialResult,
  PlanMedication,
  PlanTypeComponent,
  PlanTypeComponentMedicationCategory,
  PlanTypeComponentTestType,
  PlanTypeHeading,
  PlanType,
  PlanTypePaymentReceiptDescriptionItem,
} from '@libs/data-layer/apps/plan/entities/typeorm'
import {MilestoneToTestTypeOrPanel} from '@libs/data-layer/apps/users/entities/typeorm/milestone-to-test-type-or-panel.entity'
import {Signature} from '@libs/data-layer/apps/plan/entities/typeorm/signature.entity'
import {PatientPlanToTestTypeProcedure} from '@libs/data-layer/apps/plan/entities/typeorm/patient-plan-to-test-type-procedure.entity'
import {StaffFeedback} from '@libs/data-layer/apps/core/entities/typeorm'
import {AppointmentPartner} from '@libs/data-layer/apps/scheduling/entities/typeorm/appointment-partners.entity'
import {
  MdBillingDiagnosticCode,
  MdBillingServiceCode,
  OhipClaim,
  OhipClaimToCode,
  PatientPaymentEstimate,
  PatientPaymentEstimateEmailAttempt,
  PatientPaymentEstimateItem,
  ServiceTypeToServiceCode,
} from '@libs/data-layer/apps/clinic-billing/entities/typeorm'
import {Addon} from '@libs/data-layer/apps/scheduling/entities/typeorm/addon.entity'
import {AppointmentAddon} from '@libs/data-layer/apps/scheduling/entities/typeorm/appointment-addon.entity'
import {TestResultStatusHistory} from '@libs/data-layer/apps/clinic-test/entities/typeorm/test-result-status-history.entity'
import {EmailTemplate} from '@libs/data-layer/apps/email/entities/typeorm'
import {SmsTemplate} from '@libs/data-layer/apps/sms/entities/typeorm'
import {TestOrderStatusHistory} from '@libs/data-layer/apps/clinic-test/entities/typeorm/test-order-status-history.entity'
import {PatientPlanSpermSource} from '@libs/data-layer/apps/plan/entities/typeorm/patient-plan-sperm-source.entity'
import {TestResultComment} from '@libs/data-layer/apps/clinic-test/entities/typeorm/test-result-comment.entity'
import {PlanTypeToAutomatedTask} from '@libs/data-layer/apps/plan/entities/typeorm/plan-type-to-automated-task.entity'
import {LibraryContent} from '@libs/data-layer/apps/users/entities/typeorm/library-content.entity'
import {PlanAddon} from '@libs/data-layer/apps/plan/entities/typeorm/plan-addons.entity'
import {
  IvfTaskToDayToPlanType,
  IvfTaskToDay,
  PatientPlanCohort,
  PatientPlanCohortIvfTaskDetails,
  PatientPlanCohortIvfTaskSummary,
  PatientPlanCohortIvfTaskMatureOocyteGroupPhoto,
  PatientPlanCohortSignOffHistory,
  PatientPlanCohortIvfTaskGroup,
  IvfEmbryoGrade,
  PatientPlanCohortIvfTaskEmbryoGroupPhoto,
  PatientPlanCohortIvfTaskExpandedEmbryo,
  PatientPlanCohortIvfTaskExpandedEmbryoBiopsyAttachment,
  PatientPlanCohortIvfTaskDetailsHistory,
  EmbryoType,
  IVFCancellationReason,
  IVFUnitOption,
  IvfTaskToPlanLabInstruction,
  PatientPlanCohortIvfDish,
  IvfDishToIvfTaskGroup,
  IvfDishToPlanAddon,
  IvfDishToPlanType,
  IvfDish,
  IVFDispositionReason,
  PatientPlanCohortEggToThaw,
} from '@libs/data-layer/apps/clinic-ivf/entities'
import {AppointmentLinkedServiceProvider} from '@libs/data-layer/apps/scheduling/entities/typeorm/appointment-linked-service-provider.entity'
import {PatientPlanToEndometrialAssessment} from '@libs/data-layer/apps/plan/entities/typeorm/patient-plan-to-endometrial-assessment.entity'
import {PlanLabInstruction} from '@libs/data-layer/apps/plan/entities/typeorm/plan-lab-instruction.entity'
import {PatientPlanLabInstruction} from '@libs/data-layer/apps/plan/entities/typeorm/patient-plan-lab-instruction.entity'
import {PlanChecklist} from '@libs/data-layer/apps/plan/entities/typeorm/plan-checklist.entity'
import {PlanChecklistItem} from '@libs/data-layer/apps/plan/entities/typeorm/plan-checklist-item.entity'
import {PlanChecklistToItem} from '@libs/data-layer/apps/plan/entities/typeorm/plan-checklist-to-item.entity'
import {PatientPlanChecklistItem} from '@libs/data-layer/apps/plan/entities/typeorm/patient-plan-checklist-item.entity'
import {TestOrderComment} from '@libs/data-layer/apps/clinic-test/entities/typeorm/test-order-comment.entity'
import {TestOrderStaffActionHistory} from '@libs/data-layer/apps/clinic-test/entities/typeorm/test-order-staff-action-history.entity'
import {PaymentMethod} from '@libs/data-layer/apps/checkout/entities/typeorm'
import {PatientPlanCohortCryoSampleContainers} from '@libs/data-layer/apps/clinic-ivf/entities/patient-plan-cohort-cryo-sample-containers.entity'
import {TestTypeGroupForAnyResultTestType} from '@libs/data-layer/apps/clinic-test/entities/typeorm/test-type-group-for-any-result-test-type.entity'
import {TestTypeGroupForAnyResult} from '@libs/data-layer/apps/clinic-test/entities/typeorm/test-type-group-for-any-result.entity'
import {
  GoogleAdConversion,
  GoogleAdConversionSync,
} from '@libs/data-layer/apps/google-ads/entities/typeorm'
import {PlanTypeSheet} from '@libs/data-layer/apps/plan/entities/typeorm/plan-type-sheet.entity'
import {PatientPlanCohortFrozenEmbryoTransfer} from '@libs/data-layer/apps/clinic-ivf/entities/patient-plan-cohort-frozen-embryo-transfer.entity'
import {PlanLutealSupportItem} from '@libs/data-layer/apps/plan/entities/typeorm/plan-luteal-support-item.entity'
import {PatientPlanLutealSupportItem} from '@libs/data-layer/apps/plan/entities/typeorm/patient-plan-luteal-support-item.entity'
import {PriorityStatus} from '@libs/data-layer/apps/users/entities/typeorm/priority-status.entity'
import {PatientReport} from '@libs/data-layer/apps/clinic-test/entities/typeorm/patient-report.entity'
import {ReportType} from '@libs/data-layer/apps/clinic-test/entities/typeorm/report-type.entity'
import {TestObservationMetadata} from '@libs/data-layer/apps/clinic-test/entities/typeorm/test-observations-metadata.entity'
import {TestTypeRange} from '@libs/data-layer/apps/clinic-test/entities/typeorm/test-type-range.entity'
import {PaymentReceiptDescriptionItem} from '@libs/data-layer/apps/plan/entities/typeorm/payment-receipt-description-item.entity'
import {DefaultFilterForAppointment} from '@libs/data-layer/apps/scheduling/entities/typeorm/default-filter-for-appointment.entity'
import {DefaultFilterForAppointmentToColumn} from '@libs/data-layer/apps/scheduling/entities/typeorm/default-filter-for-appointment-to-column.entity'
import {DefaultFilterForAppointmentToServiceType} from '@libs/data-layer/apps/scheduling/entities/typeorm/default-filter-for-appointment-to-service-type.entity'
import {TestResultObservation} from '@libs/data-layer/apps/clinic-test/entities/typeorm/test-result-observation.entity'
import {TestObservationTypeResultOption} from '@libs/data-layer/apps/clinic-test/entities/typeorm/test-observation-type-result-option.entity'
import {PatientPlanAlert} from '@libs/data-layer/apps/plan/entities/typeorm/patient-plan-alert.entity'
import {PatientPlanSheetAction} from '@libs/data-layer/apps/plan/entities/typeorm/patient-plan-sheet-action.entity'
import {PlanSheetAction} from '@libs/data-layer/apps/plan/entities/typeorm/plan-sheet-action.entity'
import {PlanSheetActionList} from '@libs/data-layer/apps/plan/entities/typeorm/plan-sheet-action-list.entity'
import {PlanSheetActionListToAction} from '@libs/data-layer/apps/plan/entities/typeorm/plan-sheet-action-list-action.entity'
import {TestTypeNormalRange} from '@libs/data-layer/apps/clinic-test/entities/typeorm/test-type-normal-range.entity'
import {IvfDishBarcode} from '@libs/data-layer/apps/clinic-ivf/entities/ivf-dish-barcode.entity'
import {EncounterTypeComponent} from '@libs/data-layer/apps/users/entities/typeorm/encounter-type-component.entity'
import {
  AISummaryPrompt,
  AIReportSystemPrompt,
  AIReportUserPromptCategory,
  AIReportUserPrompt,
  AiKnowledgeBase,
  AiKnowledgeBaseCategory,
} from '@libs/data-layer/apps/ai-integrations/entities'
import {PatientEggFreezingReport} from '@libs/data-layer/apps/clinic-test/entities/typeorm/patient-egg-freezing-report.entity'
import {MedicationConsentModule} from '@libs/data-layer/apps/medication/entities/typeorm/medication-consent-module.entity'
import {PlanAddonConsentModule} from '@libs/data-layer/apps/plan/entities/typeorm/plan-addon-consent-module.entity'
import {PlanTypeConsentModule} from '@libs/data-layer/apps/plan/entities/typeorm/plan-type-consent-module.entity'
import {BillableItem} from '@libs/data-layer/apps/core/entities/typeorm/billable-item.entity'
import {PlanTypeSheetTestType} from '@libs/data-layer/apps/plan/entities/typeorm/plan-type-sheet-test-type.entity'
import {PatientPlanAddon} from '@libs/data-layer/apps/plan/entities/typeorm/patient-plan-addon.entity'
import {PushNotificationTemplate} from '@libs/data-layer/apps/notification/entities/typeorm/push-notification-template.entity'

export const entities = [
  IvfDishBarcode,
  PatientPlanCohortIvfDish,
  IvfDishToIvfTaskGroup,
  IvfDishToPlanAddon,
  IvfDishToPlanType,
  IvfDish,
  IVFCancellationReason,
  PaymentMethod,
  PatientPlanCohortIvfTaskDetailsHistory,
  IvfEmbryoGrade,
  PatientPlanCohortIvfTaskEmbryoGroupPhoto,
  PatientPlanCohortIvfTaskExpandedEmbryo,
  PatientPlanCohortIvfTaskExpandedEmbryoBiopsyAttachment,
  LabSyncRawData,
  LabSyncTestResultFieldMatch,
  LabSyncObservationRequest,
  LabSyncObservationRequestStatusHistory,
  LabSyncObservationResult,
  PatientAdhocPayment,
  TestOrderAction,
  SuperType,
  TaskTemplate,
  MdBillingDiagnosticCode,
  MdBillingServiceCode,
  OhipClaim,
  OhipClaimToCode,
  ServiceTypeToServiceCode,
  TestOrderStatusHistory,
  PatientFamilyHealthProblem,
  AnswerOption,
  Appointment,
  Patient,
  PatientQuestionnaireAnswer,
  QuestionConstraint,
  ServiceProvider,
  QuestionnaireToQuestion,
  Questionnaire,
  ServiceCategory,
  ServiceGroup,
  Question,
  ApplicationCode,
  PaymentOrder,
  PaymentOrderItem,
  ServiceType,
  SchedulingTemplate,
  SchedulingTemplatePeriod,
  PatientScheduledMilestone,
  SchedulingSlot,
  ServiceGroupAvailability,
  PatientEncounterAddendum,
  PatientEncounterAddendumAttachment,
  PatientEncounter,
  PatientEncounterAttachment,
  EncounterType,

  PatientStaffNoteAddendum,
  PatientStaffNoteAddendumAttachment,
  PatientStaffNote,
  PatientStaffNoteAttachment,
  StaffNoteType,
  StaffDefault,

  StaffNoteType,
  PatientPartner,
  AppliedSchedulingTemplatePeriod,
  Introduction,
  ServiceGroupToServiceType,
  ServiceGroupToApplicationCode,
  ServiceProviderToServiceType,
  PatientPlanToTestTypeProcedure,
  ServiceTypeConstraint,
  PatientDetail,
  PatientMedication,
  TestResult,
  LabInfo,
  ProfileTestResult,
  TestPanel,
  TestPanelToTestType,
  TestResultAttachment,
  TestResultMeasurement,
  TestResultObUltrasound,
  TestType,
  CareTeam,
  PatientPrescription,
  Pharmacy,
  ServiceProviderGroup,
  Medication,
  MedicationInstruction,
  PatientToServiceProvider,
  MedicationInstructionStep,
  PatientDetailFemale,
  PatientFullTermDeliveryHistory,
  PatientPreTermDeliveryHistory,
  PatientMiscarriageHistory,
  PatientEctopicPregnancyHistory,
  PatientAbortionHistory,
  SpecimenGroup,
  LabMachine,
  Specimen,
  SpecimenStorageLocation,
  SpecimenTest,
  TransportFolder,
  AfterVisitSummary,
  PatientMilestone,
  TestOrderType,
  TestOrder,
  TestOrderItem,
  TestGroup,
  TestGroupItem,
  TestOrderCancellationReason,
  TestTypeResultOption,
  PatientDefaultMilestone,
  ConsentModule,
  PredefinedConsentPackage,
  PredefinedConsentPackageToModule,
  PatientQuestionnaire,
  PatientQuestionnaireToQuestion,
  ConsentModuleToQuestion,
  LibraryContent,
  PatientAlert,
  PatientMilestoneToAppointment,
  PatientAddress,
  SpecimenIncompletionReason,
  Task,
  Staff,
  TaskReassignment,
  PatientDetailMale,
  PatientPastSurgery,
  PatientPreviousFertilityTreatment,
  PatientVitaminSupplement,
  PatientNote,
  PatientCustomAlert,
  PatientContactForm,
  MedicationCategory,
  MedicationToMedicationCategory,
  PatientPlan,
  PlanCategory,
  PlanInitialResult,
  PatientPlanStatus,
  PlanMedication,
  PlanType,
  PatientDoctor,
  PatientPushNotification,
  PatientReferral,
  SemenVerificationForm,
  MilestoneToTestTypeOrPanel,
  Role,
  Permission,
  AutomatedTask,
  Signature,
  CatheterType,
  AppointmentPartner,
  TestResultOvaryMeasurement,
  TestResultOvaryCystMeasurement,
  TestResultOHSSOvaryMeasurement,
  TestResultOHSSFluidMeasurement,
  StaffFeedback,
  PatientDocument,
  DocumentCategory,
  CryoTank,
  CryoCan,
  CryoCane,
  CryoTankV2,
  CryoCanV2,
  CryoCaneV2,
  CryoSampleDonor,
  CryoSampleContainer,
  CryoInventoryCard,
  CryoInventoryCardExternalSample,
  CryoVial,
  CryoDiscardReason,
  Reagent,
  MediaLot,
  MilestoneServiceTypeLimitation,
  TestResultUterusMeasurement,
  TestResultUltrasoundFinalReport,
  PatientPlanDiscontinuedMedication,
  PatientPlanSheet,
  EmailTemplate,
  SmsTemplate,
  PushNotificationTemplate,
  Addon,
  AppointmentAddon,
  TestResultStatusHistory,
  PatientPlanDetail,
  PatientPlanSpermSource,
  TestResultComment,
  PlanTypeToAutomatedTask,
  PlanAddon,
  IvfTaskToDayToPlanType,
  IvfTaskToDay,
  PatientPlanCohort,
  PatientPlanCohortIvfTaskDetails,
  PatientPlanCohortIvfTaskSummary,
  PatientPlanCohortIvfTaskMatureOocyteGroupPhoto,
  PatientPlanCohortSignOffHistory,
  PatientPlanCohortIvfTaskGroup,
  AppointmentLinkedServiceProvider,
  PatientPlanToEndometrialAssessment,
  PatientPlanSheetAdditionalDay,
  PlanLabInstruction,
  PatientPlanLabInstruction,
  PlanChecklist,
  PlanChecklistItem,
  PlanChecklistToItem,
  PatientPlanChecklistItem,
  PatientPlanGeneticTesting,
  PatientPlanEmbryoTypeTransferInstruction,
  EmbryoType,
  TestOrderComment,
  TestOrderStaffActionHistory,
  MedicationPredifinedDosage,
  PlanTypeComponent,
  PlanTypeHeading,
  PlanTypeComponentMedicationCategory,
  PlanTypeComponentTestType,
  PatientPlanChangeNotificationEntity,
  PatientPlanCohortCryoSampleContainers,
  PatientPlanCohortFrozenEmbryoTransfer,
  TestTypeGroupForAnyResult,
  TestTypeGroupForAnyResultTestType,
  GoogleAdConversionSync,
  GoogleAdConversion,
  AppointmentMetadata,
  DefaultFilterForAppointment,
  DefaultFilterForAppointmentToColumn,
  DefaultFilterForAppointmentToServiceType,
  PlanTypeSheet,
  ThyroidProtocolResult,
  ThyroidProtocolResultNote,
  SchedulingTimeOffBlock,
  PlanLutealSupportItem,
  PatientPlanLutealSupportItem,
  IVFUnitOption,
  ProfileAlert,
  PatientProfileAlert,
  PatientFertilityIQ,
  PatientFertilityIQFemale,
  TestResultSonoDetail,
  PatientFertilityIQTestResult,
  IvfTaskToPlanLabInstruction,
  PriorityStatus,
  PatientReport,
  ReportType,
  TestObservationMetadata,
  TestTypeRange,
  TestTypeNormalRange,
  PaymentReceiptDescriptionItem,
  PlanTypePaymentReceiptDescriptionItem,
  TestTypeConfiguration,
  BulkDownloadRequest,
  BulkDownloadRequestItem,
  PatientFeedbackForm,
  TestObservationType,
  TestResultObservation,
  TestTypeObservationType,
  TestObservationTypeResultOption,
  PatientPlanAlert,
  PatientPlanSheetAction,
  PlanSheetAction,
  PlanSheetActionList,
  PlanSheetActionListToAction,
  SchedulingTimeOffBlockPeriod,
  DefaultFilterForAppointmentToPatientStatus,
  DefaultFilterForAppointmentToServiceProvider,
  ExternalDoctor,
  PatientCryoSubscription,
  PatientCryoSubscriptionEvent,
  EncounterTypeComponent,
  AISummaryPrompt,
  AIReportSystemPrompt,
  AIReportUserPromptCategory,
  AIReportUserPrompt,
  AiKnowledgeBase,
  AiKnowledgeBaseCategory,
  SpecimenDetailSyncStatusLog,
  PatientEggFreezingReport,
  MedicationConsentModule,
  PlanAddonConsentModule,
  PlanTypeConsentModule,
  PatientConsentModule,
  PatientConsentPackage,
  PatientConsentPackageSignatory,
  IVFDispositionReason,
  PatientPlanCohortEggToThaw,
  BillableItem,
  PlanTypeSheetTestType,
  PatientPlanAddon,
  PatientPaymentEstimate,
  PatientPaymentEstimateEmailAttempt,
  PatientPaymentEstimateItem,
]
